include:
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/packaging.yml'
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/_deployment.yml'

stages:
  - package
  - test-package
  - deploy

variables:
  STACK: elastic

.deploy:
  variables:
    SERVICES_TO_CHECK: ${STACK}_${SERVICE_NAME}
  script:
    - mkdir -p deploy/certs deploy/config
    - echo "${CA_PEM}" > "deploy/certs/root-ca.pem"
    - echo "${CA_KEY}" > "deploy/certs/root-ca.key"
    - echo "${NODE_PEM}" > "deploy/certs/node.pem"
    - echo "${NODE_KEY}" > "deploy/certs/node.key"
    - echo "${NODE_CSR}" > "deploy/certs/node.csr"
    - echo "${ADMIN_PEM}" > "deploy/certs/admin.pem"
    - echo "${ADMIN_KEY}" > "deploy/certs/admin.key"
    - echo "${ADMIN_CSR}" > "deploy/certs/admin.csr"
    - echo "${SG_USERS}" > "deploy/config/sg_internal_users.yml"
    - >
      deploy.sh IMAGE_NAME=${IMAGE_NAME} IMAGE_TAG=${IMAGE_TAG} COMPOSE_FILE=${COMPOSE_FILE} SG_ADMIN_DN=${SG_ADMIN_DN}
      SG_NODE_1_DN=${SG_NODE_1_DN} SG_NODE_2_DN=${SG_NODE_2_DN} SG_NODE_3_DN=${SG_NODE_3_DN} AWS_REGION=${AWS_REGION}
      S3_ACCESS_KEY=${S3_ACCESS_KEY} S3_SECRET_KEY=${S3_SECRET_KEY}

.deploy-development:
  variables:
    COMPOSE_FILE: docker-compose.${SERVICE_NAME}.tmpl.yml:docker-compose.${SERVICE_NAME}.dev.yml
  environment:
    name: dev/${SERVICE_NAME}

.deploy-production:
  variables:
    COMPOSE_FILE: docker-compose.${SERVICE_NAME}.tmpl.yml:docker-compose.${SERVICE_NAME}.prod.yml
  environment:
    name: pro/${SERVICE_NAME}

.deploy-es6-1:
  variables: &deploy-es6-1-variables
    SERVICE_NAME: es6-1
    NODE_PEM: ${NODE_1_PEM}
    NODE_KEY: ${NODE_1_KEY}
    NODE_CSR: ${NODE_1_CSR}

.deploy-es6-2:
  variables: &deploy-es6-2-variables
    SERVICE_NAME: es6-2
    NODE_PEM: ${NODE_2_PEM}
    NODE_KEY: ${NODE_2_KEY}
    NODE_CSR: ${NODE_2_CSR}

.deploy-es6-3:
  variables: &deploy-es6-3-variables
    SERVICE_NAME: es6-3
    NODE_PEM: ${NODE_3_PEM}
    NODE_KEY: ${NODE_3_KEY}
    NODE_CSR: ${NODE_3_CSR}

.deploy-es6-1-development:
  extends: .deploy-development
  variables: *deploy-es6-1-variables

.deploy-es6-2-development:
  extends: .deploy-development
  variables: *deploy-es6-2-variables

.deploy-es6-3-development:
  extends: .deploy-development
  variables: *deploy-es6-3-variables

.deploy-es6-1-production:
  extends: .deploy-production
  variables: *deploy-es6-1-variables

.deploy-es6-2-production:
  extends: .deploy-production
  variables: *deploy-es6-2-variables

.deploy-es6-3-production:
  extends: .deploy-production
  variables: *deploy-es6-3-variables

deploy-es6-1-support-branch-development:
  extends: .deploy-es6-1-development
  only:
    - branches
  except:
    - master
    - schedules

deploy-es6-2-support-branch-development:
  extends: .deploy-es6-2-development
  only:
    - branches
  except:
    - master
    - schedules

deploy-es6-3-support-branch-development:
  extends: .deploy-es6-3-development
  only:
    - branches
  except:
    - master
    - schedules

deploy-es6-1-stable-branch-development:
  extends: .deploy-es6-1-development
  only:
    - master
  except:
    - schedules

deploy-es6-2-stable-branch-development:
  extends: .deploy-es6-2-development
  only:
    - master
  except:
    - schedules

deploy-es6-3-stable-branch-development:
  extends: .deploy-es6-3-development
  only:
    - master
  except:
    - schedules

deploy-es6-1-support-branch-production:
  extends: .deploy-es6-1-production
  only:
    - branches
  except:
    - master
    - schedules

deploy-es6-2-support-branch-production:
  extends: .deploy-es6-2-production
  only:
    - branches
  except:
    - master
    - schedules

deploy-es6-3-support-branch-production:
  extends: .deploy-es6-3-production
  only:
    - branches
  except:
    - master
    - schedules

deploy-es6-1-stable-branch-production:
  extends: .deploy-es6-1-production
  only:
    - master
  except:
    - schedules

deploy-es6-2-stable-branch-production:
  extends: .deploy-es6-2-production
  only:
    - master
  except:
    - schedules

deploy-es6-3-stable-branch-production:
  extends: .deploy-es6-3-production
  only:
    - master
  except:
    - schedules
