version: '3.5'

services:
  elasticsearch:
    networks:
      elastic-net:
        aliases:
          - es-{{.Task.Slot}}
    environment:
      - ES_CLUSTER_NAME=redmic
      - ES_NODE_NAME=elasticsearch-{{.Task.Slot}}
      - ES_DISCOVERY_ZEN_PING_UNICAST_HOSTS=['tasks.elasticsearch']
    deploy:
      mode: replicated
      replicas: 3
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        max_attempts: 3

volumes:
  elasticsearch-vol:
    name: "elasticsearch-{{.Task.Slot}}-vol"
    driver: "cloudstor:aws"
    driver_opts:
      backing: relocatable
      size: 25
      ebstype: gp2
