version: '3.5'

services:
  elasticsearch-1:
    environment:
      - ES_CLUSTER_NAME=redmic
      - ES_NODE_NAME={{.Service.Name}}
      - ES_DISCOVERY_ZEN_PING_UNICAST_HOSTS=['elasticsearch-1', 'elasticsearch-2', 'elasticsearch-3']
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
          - node.labels.workerid == 1
      restart_policy:
        condition: on-failure
        max_attempts: 3

  elasticsearch-2:
    environment:
      - ES_CLUSTER_NAME=redmic
      - ES_NODE_NAME={{.Service.Name}}
      - ES_DISCOVERY_ZEN_PING_UNICAST_HOSTS=['elasticsearch-1', 'elasticsearch-2', 'elasticsearch-3']
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
          - node.labels.workerid == 2
      restart_policy:
        condition: on-failure
        max_attempts: 3

  elasticsearch-3:
    environment:
      - ES_CLUSTER_NAME=redmic
      - ES_NODE_NAME={{.Service.Name}}
      - ES_DISCOVERY_ZEN_PING_UNICAST_HOSTS=['elasticsearch-1', 'elasticsearch-2', 'elasticsearch-3']
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
          - node.labels.workerid == 3
      restart_policy:
        condition: on-failure
        max_attempts: 3

volumes:
  elasticsearch-1-vol:
    name: "elasticsearch-1-vol"
    driver: "cloudstor:aws"
    driver_opts:
      backing: relocatable
      size: 25
      ebstype: gp2

  elasticsearch-2-vol:
    name: "elasticsearch-2-vol"
    driver: "cloudstor:aws"
    driver_opts:
      backing: relocatable
      size: 25
      ebstype: gp2

  elasticsearch-3-vol:
    name: "elasticsearch-3-vol"
    driver: "cloudstor:aws"
    driver_opts:
      backing: relocatable
      size: 25
      ebstype: gp2
