version: '3.5'

services:
  elasticsearch-1:
    container_name: elasticsearch-1
    restart: on-failure:3
    ports:
      - ${PORT1}:${PORT1}
      - ${PORT2}:${PORT2}
    environment:
      - ES_CLUSTER_NAME=elasticsearch_dev
      - ES_NODE_NAME=node-1
      - ES_DISCOVERY_ZEN_MINIMUM_MASTER_NODES=1
      - ES_DISCOVERY_ZEN_PING_UNICAST_HOSTS=elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1

volumes:
  elasticsearch-1-vol:
    name: elasticsearch-vol
