version: '3.5'

services:
  elastic-search:
    networks:
      elastic-net:
        aliases:
          - es-{{.Task.Slot}}
    ports:
      - ${PORT1}
      - ${PORT2}
    environment:
      - SWARM_MODE=true
      - SERVICE_NAME={{.Service.Name}}
      - ES_CLUSTER_NAME=redmic
      - ES_NODE_NAME={{.Service.Name}}-{{.Task.Slot}}
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        max_attempts: 3

volumes:
  elastic-search-vol:
    name: "elastic-search-{{.Task.Slot}}-vol"
    driver: "cloudstor:aws"
    driver_opts:
      backing: relocatable
      size: 25
      ebstype: io1
      iops: 100
