services:
  elasticsearch:
    environment:
      ES_JAVA_OPTS: ${ES_JAVA_OPTS:--Xms2g -Xmx2g}
      cluster.name: ${ES_CLUSTER_NAME:-es_pro}
      TAKE_FILE_OWNERSHIP: '1000:0'
    deploy:
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-2}'
          memory: ${RESOURCES_LIMITS_MEMORY:-4G}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.2}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-3G}

volumes:
  data-vol:
    name: ${DATA_VOL_NAME}-{{.Node.Hostname}}
    driver: ${PRO_VOL_DRIVER}
    driver_opts:
      backing: relocatable
      size: ${DATA_VOL_SIZE:-25}
      ebstype: gp3

  conf-vol:
    name: ${CONF_VOL_NAME}-{{.Node.Hostname}}
    driver: ${PRO_VOL_DRIVER}
    driver_opts:
      backing: shared
      perfmode: maxio

  cert-vol:
    name: ${CERT_VOL_NAME}
    driver: ${PRO_VOL_DRIVER}
    driver_opts:
      backing: shared
