version: '3.5'

services:
  es6-3:
    environment:
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - cluster.name=${ES_CLUSTER_NAME:-es_pro}
      - discovery.zen.minimum_master_nodes=${ES_DISCOVERY_ZEN_MINIMUM_MASTER_NODES:-2}
      - TAKE_FILE_OWNERSHIP=1000:0
    deploy:
      placement:
        constraints:
          - node.role == worker
          - engine.labels.availability_zone == ${AWS_REGION}c
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          memory: 1639M

volumes:
  es-data-vol:
    name: "${ES_DATA_VOL_NAME:-es6-3-data-vol}"
    driver: "cloudstor:aws"
    driver_opts:
      backing: relocatable
      size: 25
      ebstype: gp2

  es-conf-vol:
    name: "${ES_CONF_VOL_NAME:-es6-3-conf-vol}"
    driver: "cloudstor:aws"
    driver_opts:
      backing: shared
      perfmode: maxio
