version: '3.5'

services:
  es6-3:
    image: ${IMAGE_NAME}:${IMAGE_TAG:-latest}
    environment:
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - node.name=${ES_NODE_NAME:-es6-3}
      - node.master=${ES_NODE_MASTER}
      - node.data=${ES_NODE_DATA}
      - node.ingest=${ES_NODE_INGEST}
      - path.data=${ES_PATH_DATA}
      - network.host=${ES_NETWORK_HOST}
      - bootstrap.memory_lock=${ES_BOOTSTRAP_MEMORY_LOCK}
      - discovery.zen.ping.unicast.hosts=${ES_DISCOVERY_ZEN_PING_UNICAST_HOSTS:-['es6-1', 'es6-2']}
    networks:
      elastic6-net:
        aliases:
          - es6-3
    volumes:
      - es-data-vol:${ES_PATH_DATA}
      - es-conf-vol:/usr/share/elasticsearch/config
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        delay: 1m
        window: 3m
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          memory: 1639M
    healthcheck:
      test: curl --fail --silent localhost:${PORT}/_cluster/health
      timeout: 10s
      retries: 3
      start_period: 2m

networks:
  elastic6-net:
    name: elastic6-net
    driver: overlay
    attachable: true
