version: '3.5'

services:
  es6-1:
    image: ${IMAGE_NAME}:${IMAGE_TAG:-latest}
    environment:
      - node.name=${ES_NODE_NAME:-es6-1}
      - node.master=${ES_NODE_MASTER}
      - node.data=${ES_NODE_DATA}
      - node.ingest=${ES_NODE_INGEST}
      - path.data=${ES_PATH_DATA}
      - network.host=${ES_NETWORK_HOST}
      - bootstrap.memory_lock=${ES_BOOTSTRAP_MEMORY_LOCK}
      - xpack.security.enabled=false
      - searchguard.nodes_dn.0=${SG_NODE_1_DN}
      - searchguard.nodes_dn.1=${SG_NODE_2_DN}
      - searchguard.nodes_dn.2=${SG_NODE_3_DN}
      - searchguard.authcz.admin_dn.0=${SG_ADMIN_DN}
      - searchguard.ssl.transport.pemcert_filepath=certs/node.pem
      - searchguard.ssl.transport.pemkey_filepath=certs/node.key
      - searchguard.ssl.transport.pemtrustedcas_filepath=certs/root-ca.pem
      - searchguard.ssl.transport.enforce_hostname_verification=false
      - searchguard.ssl.transport.resolve_hostname=false
      - searchguard.ssl.http.enabled=false
      - searchguard.ssl.http.pemcert_filepath=certs/node.pem
      - searchguard.ssl.http.pemkey_filepath=certs/node.key
      - searchguard.ssl.http.pemtrustedcas_filepath=certs/root-ca.pem
      - searchguard.enable_snapshot_restore_privilege=true
      - searchguard.enterprise_modules_enabled=false
      - discovery.zen.ping.unicast.hosts=${ES_DISCOVERY_ZEN_PING_UNICAST_HOSTS:-es6-2,es6-3}
      - S3_ACCESS_KEY
      - S3_SECRET_KEY
    networks:
      elastic-net:
        aliases:
          - ${ELASTIC_NET_ALIAS:-es6-1}
      metric-net:
    volumes:
      - es-data-vol:${ES_PATH_DATA}
      - es-conf-vol:/usr/share/elasticsearch/config
    secrets:
      - source: ca-pem
        target: /usr/share/elasticsearch/config/certs/root-ca.pem
        mode: 0600
        uid: '1000'
        gid: '1000'
      - source: ca-key
        target: /usr/share/elasticsearch/config/certs/root-ca.key
        mode: 0600
        uid: '1000'
        gid: '1000'
      - source: node-pem
        target: /usr/share/elasticsearch/config/certs/node.pem
        mode: 0600
        uid: '1000'
        gid: '1000'
      - source: node-key
        target: /usr/share/elasticsearch/config/certs/node.key
        mode: 0600
        uid: '1000'
        gid: '1000'
      - source: node-csr
        target: /usr/share/elasticsearch/config/certs/node.csr
        mode: 0600
        uid: '1000'
        gid: '1000'
      - source: admin-pem
        target: /usr/share/elasticsearch/config/certs/admin.pem
        mode: 0600
        uid: '1000'
        gid: '1000'
      - source: admin-key
        target: /usr/share/elasticsearch/config/certs/admin.key
        mode: 0600
        uid: '1000'
        gid: '1000'
      - source: admin-csr
        target: /usr/share/elasticsearch/config/certs/admin.csr
        mode: 0600
        uid: '1000'
        gid: '1000'
    configs:
      - source: sg-users
        target: /usr/share/elasticsearch/plugins/search-guard-6/sgconfig/sg_internal_users.yml
        mode: 0600
        uid: '1000'
        gid: '1000'
      - source: sg-config
        target: /usr/share/elasticsearch/plugins/search-guard-6/sgconfig/sg_config.yml
        mode: 0600
        uid: '1000'
        gid: '1000'
      - source: sg-roles
        target: /usr/share/elasticsearch/plugins/search-guard-6/sgconfig/sg_roles.yml
        mode: 0600
        uid: '1000'
        gid: '1000'
      - source: sg-roles-mapping
        target: /usr/share/elasticsearch/plugins/search-guard-6/sgconfig/sg_roles_mapping.yml
        mode: 0600
        uid: '1000'
        gid: '1000'
    logging:
      driver: json-file
    healthcheck:
      test: "[[ $$(curl --silent localhost:${PORT}/_cat/health?h=status) =~ ^(red|yellow) ]]"
      interval: 30s
      timeout: 1m
      retries: 20
      start_period: 2m
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        delay: 30s
        window: 3m

networks:
  elastic-net:
    name: ${ELASTIC_NET_NAME:-elastic6-net}
    driver: overlay
    attachable: true

  metric-net:
    name: ${METRIC_NET_NAME:-metric-net}
    external: true

secrets:
  ca-pem:
    name: ${CA_PEM_NAME:-ca-pem}
    file: ./certs/root-ca.pem

  ca-key:
    name: ${CA_KEY_NAME:-ca-key}
    file: ./certs/root-ca.key

  node-pem:
    name: ${NODE_PEM_NAME:-node-pem}
    file: ./certs/node.pem

  node-key:
    name: ${NODE_KEY_NAME:-node-key}
    file: ./certs/node.key

  node-csr:
    name: ${NODE_CSR_NAME:-node-csr}
    file: ./certs/node.csr

  admin-pem:
    name: ${ADMIN_PEM_NAME:-admin-pem}
    file: ./certs/admin.pem

  admin-key:
    name: ${ADMIN_KEY_NAME:-admin-key}
    file: ./certs/admin.key

  admin-csr:
    name: ${ADMIN_CSR_NAME:-admin-csr}
    file: ./certs/admin.csr

configs:
  sg-users:
    name: ${SG_USERS_NAME:-sg-users}
    file: ./config/sg_internal_users.yml

  sg-config:
    name: ${SG_CONFIG_NAME:-sg-config}
    file: ./config/sg_config.yml

  sg-roles:
    name: ${SG_ROLES_NAME:-sg-roles}
    file: ./config/sg_roles.yml

  sg-roles-mapping:
    name: ${SG_ROLES_MAPPING_NAME:-sg-roles-mapping}
    file: ./config/sg_roles_mapping.yml
