version: '3.5'

services:
  es6-1:
    environment:
      - cluster.name=${ES_CLUSTER_NAME:-es_pro}
      - discovery.zen.minimum_master_nodes=${ES_DISCOVERY_ZEN_MINIMUM_MASTER_NODES:-2}
      - cloud.aws.s3.access_key=${ES_CLOUD_AWS_S3_ACCESS_KEY}
      - cloud.aws.s3.secret_key=${ES_CLOUD_AWS_S3_SECRET_KEY}
    deploy:
      placement:
        constraints:
          - node.role == worker
          - engine.labels.availability_zone == ${AWS_REGION}a

volumes:
  es-data-vol:
    name: "${ES_DATA_VOL_NAME:-es6-1-data-vol}"
    driver: "cloudstor:aws"
    driver_opts:
      backing: relocatable
      size: 25
      ebstype: gp2

  es-conf-vol:
    name: "${ES_CONF_VOL_NAME:-es6-1-conf-vol}"
    driver: "cloudstor:aws"
    driver_opts:
      backing: shared
      perfmode: maxio