version: '3.5'

services:
  es6-3:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    environment:
      node.name: ${ES_NODE_NAME:-es6-3}
      node.master: ${ES_NODE_MASTER}
      node.data: ${ES_NODE_DATA}
      node.ingest: ${ES_NODE_INGEST}
      path.data: ${ES_PATH_DATA}
      network.host: ${ES_NETWORK_HOST}
      bootstrap.memory_lock: ${ES_BOOTSTRAP_MEMORY_LOCK}
      xpack.security.enabled: ${ES_XPACK_SECURITY_ENABLED}
      searchguard.nodes_dn.0: ${SG_NODE_1_DN}
      searchguard.nodes_dn.1: ${SG_NODE_2_DN}
      searchguard.nodes_dn.2: ${SG_NODE_3_DN}
      searchguard.authcz.admin_dn.0: ${SG_ADMIN_DN}
      searchguard.ssl.transport.pemcert_filepath: ${ES_SEARCHGUARD_SSL_TRANSPORT_PEMCERT_FILEPATH}
      searchguard.ssl.transport.pemkey_filepath: ${ES_SEARCHGUARD_SSL_TRANSPORT_PEMKEY_FILEPATH}
      searchguard.ssl.transport.pemtrustedcas_filepath: ${ES_SEARCHGUARD_SSL_TRANSPORT_PEMTRUSTEDCAS_FILEPATH}
      searchguard.ssl.transport.enforce_hostname_verification: ${ES_SEARCHGUARD_SSL_TRANSPORT_ENFORCE_HOSTNAME_VERIFICATION}
      searchguard.ssl.transport.resolve_hostname: ${ES_SEARCHGUARD_SSL_TRANSPORT_RESOLVE_HOSTNAME}
      searchguard.ssl.http.enabled: ${ES_SEARCHGUARD_SSL_HTTP_ENABLED}
      searchguard.ssl.http.pemcert_filepath: ${ES_SEARCHGUARD_SSL_HTTP_PEMCERT_FILEPATH}
      searchguard.ssl.http.pemkey_filepath: ${ES_SEARCHGUARD_SSL_HTTP_PEMKEY_FILEPATH}
      searchguard.ssl.http.pemtrustedcas_filepath: ${ES_SEARCHGUARD_SSL_HTTP_PEMTRUSTEDCAS_FILEPATH}
      searchguard.enable_snapshot_restore_privilege: ${ES_SEARCHGUARD_ENABLE_SNAPSHOT_RESTORE_PRIVILEGE}
      searchguard.enterprise_modules_enabled: ${ES_SEARCHGUARD_ENTERPRISE_MODULES_ENABLED}
      discovery.zen.ping.unicast.hosts: ${ES_DISCOVERY_ZEN_PING_UNICAST_HOSTS:-es6-1,es6-2}
      S3_ACCESS_KEY:
      S3_SECRET_KEY:
    networks:
      elastic-net:
        aliases:
          - ${ELASTIC_NET_ALIAS:-es6-3}
      metric-net:
    volumes:
      - es-data-vol:${ES_PATH_DATA}
      - es-conf-vol:${ES_CONFIG_PATH}
    secrets:
      - source: ca-pem
        target: ${ES_CERT_PATH}/root-ca.pem
        mode: 0600
        uid: '${SG_FILE_UID}'
        gid: '${SG_FILE_GID}'
      - source: ca-key
        target: ${ES_CERT_PATH}/root-ca.key
        mode: 0600
        uid: '${SG_FILE_UID}'
        gid: '${SG_FILE_GID}'
      - source: node-pem
        target: ${ES_CERT_PATH}/node.pem
        mode: 0600
        uid: '${SG_FILE_UID}'
        gid: '${SG_FILE_GID}'
      - source: node-key
        target: ${ES_CERT_PATH}/node.key
        mode: 0600
        uid: '${SG_FILE_UID}'
        gid: '${SG_FILE_GID}'
      - source: node-csr
        target: ${ES_CERT_PATH}/node.csr
        mode: 0600
        uid: '${SG_FILE_UID}'
        gid: '${SG_FILE_GID}'
    logging:
      driver: json-file
    healthcheck:
      test: "[[ $$(curl --silent localhost:${PORT}/_cat/health?h=status) =~ ^(green|yellow) ]]"
      interval: ${HEALTHCHECK_INTERVAL:-30s}
      timeout: ${HEALTHCHECK_TIMEOUT:-1m}
      retries: ${HEALTHCHECK_RETRIES:-20}
      start_period: ${HEALTHCHECK_START_PERIOD:-2m}
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}
      restart_policy:
        delay: ${RESTART_DELAY:-5s}
      update_config:
        delay: ${UPDATE_DELAY:-3m}

networks:
  elastic-net:
    name: ${ELASTIC_NET_NAME}
    driver: ${ELASTIC_NET_DRIVER}
    external: true

  metric-net:
    name: ${METRIC_NET_NAME}
    driver: ${METRIC_NET_DRIVER}
    external: true

secrets:
  ca-pem:
    name: ${CA_PEM_NAME}
    external: true

  ca-key:
    name: ${CA_KEY_NAME}
    external: true

  node-pem:
    name: ${NODE_PEM_NAME:-node-3-pem}
    file: ./certs/node.pem

  node-key:
    name: ${NODE_KEY_NAME:-node-3-key}
    file: ./certs/node.key

  node-csr:
    name: ${NODE_CSR_NAME:-node-3-csr}
    file: ./certs/node.csr
