version: '3.5'

services:
  elasticsearch-1:
    environment:
      - ES_JAVA_OPTS=-Xms1g -Xmx1g -Djava.security.policy=file:///usr/share/elasticsearch/config/grovy-classes_whitelist.policy
      - ES_CLUSTER_NAME=redmic
      - ES_NODE_NAME={{.Service.Name}}
      - ES_DISCOVERY_ZEN_PING_UNICAST_HOSTS=['elasticsearch-1', 'elasticsearch-2', 'elasticsearch-3']
      - USER_MANAGEMENT_DELAY=200
      - ES_XPACK_SECURITY_ENABLED
    healthcheck:
      test: curl --silent localhost:${PORT}/_cluster/health
      timeout: 10s
      retries: 3
      start_period: 2m
    deploy:
      placement:
        constraints:
          - node.role == worker
          - engine.labels.availability_zone == ${AWS_REGION}a

volumes:
  elasticsearch-vol:
    name: "elasticsearch-1-vol"
    driver: "cloudstor:aws"
    driver_opts:
      backing: relocatable
      size: 25
      ebstype: gp2
