version: '3.5'

services:
  elasticsearch-1:
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m -Djava.security.policy=file:///usr/share/elasticsearch/config/grovy-classes_whitelist.policy
      - ES_CLUSTER_NAME=elasticsearch_dev
      - ES_NODE_NAME=node-1
      - ES_DISCOVERY_ZEN_MINIMUM_MASTER_NODES=1
      - ES_DISCOVERY_ZEN_PING_UNICAST_HOSTS=elasticsearch-1
      - ES_XPACK_SECURITY_ENABLED=false
    ports:
      - target: ${PORT1}
        published: ${PORT1}
        mode: host
      - target: ${PORT2}
        published: ${PORT2}
        mode: host

volumes:
  elasticsearch-vol:
    name: elasticsearch-vol
