version: '3.5'

services:
  elasticsearch-1:
    image: ${IMAGE_NAME}:${IMAGE_TAG:-latest}
    networks:
      elastic-net:
        aliases:
          - es-1
    volumes:
      - elasticsearch-vol:/usr/share/elasticsearch/data
    environment:
      - ES_BOOTSTRAP_MEMORY_LOCK=true
      - ES_PLUGINS
      - OLD_ELASTIC_ADMIN_PASS
      - ELASTIC_ADMIN_PASS
      - ELASTIC_USER
      - ELASTIC_USER_PASS
      - ELASTIC_USER_ROLE
    healthcheck:
      test: >
        status=$$(curl --write-out %{http_code} --silent --output /dev/null -u "${ELASTIC_USER}:${ELASTIC_USER_PASS}" localhost:${PORT1}/_cluster/health);
        [ "$${status}" -eq "200" ] || [ "$${status}" -eq "401" ]
      timeout: 10s
      retries: 3
      start_period: 2m

networks:
  elastic-net:
    external: true
