version: '3.5'

services:
  es6-3:
    environment:
      ES_JAVA_OPTS: ${ES_JAVA_OPTS:--Xms2g -Xmx2g}
      cluster.name: ${ES_CLUSTER_NAME:-es_pro}
      TAKE_FILE_OWNERSHIP: '1000:0'
    deploy:
      placement:
        constraints:
          - node.role == worker
          - engine.labels.availability_zone == ${AWS_REGION}c
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-2}'
          memory: ${RESOURCES_LIMITS_MEMORY:-4G}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.2}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-3G}

volumes:
  es-data-vol:
    name: ${ES_DATA_VOL_NAME:-es6-3-data-vol}
    driver: 'cloudstor:aws'
    driver_opts:
      backing: relocatable
      size: 25
      ebstype: gp2

  es-conf-vol:
    name: ${ES_CONF_VOL_NAME:-es6-3-conf-vol}
    driver: 'cloudstor:aws'
    driver_opts:
      backing: shared
      perfmode: maxio
