version: '3.5'

services:
  elasticsearch-3:
    image: ${IMAGE_NAME}:${IMAGE_TAG:-latest}
    networks:
      elastic-net:
        aliases:
          - es-3
    volumes:
      - elasticsearch-vol:/usr/share/elasticsearch/data
    environment:
      - ES_JAVA_OPTS=-Xms1g -Xmx1g -Djava.security.policy=file:///usr/share/elasticsearch/config/grovy-classes_whitelist.policy
      - ES_CLUSTER_NAME=redmic
      - ES_NODE_NAME={{.Service.Name}}
      - ES_DISCOVERY_ZEN_PING_UNICAST_HOSTS=['elasticsearch-1', 'elasticsearch-2', 'elasticsearch-3']
      - USER_MANAGEMENT_DELAY=200
      - ES_XPACK_SECURITY_ENABLED
      - ES_BOOTSTRAP_MEMORY_LOCK=true
      - ES_PLUGINS
      - OLD_ELASTIC_ADMIN_PASS
      - ELASTIC_ADMIN_PASS
      - ELASTIC_USER
      - ELASTIC_USER_PASS
      - ELASTIC_USER_ROLE
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
          - engine.labels.availability_zone == ${AWS_REGION}c
      restart_policy:
        condition: on-failure
        delay: 1m
        window: 3m
      resources:
        limits:
          cpus: '1'
          memory: 2G
        reservations:
          memory: 1639M

networks:
  elastic-net:
    external: true
