version: '3.5'

services:
  es6-2:
    environment:
      - cluster.name=es_pro
      - discovery.zen.minimum_master_nodes=2
      - discovery.zen.ping.unicast.hosts=['es6-1', 'es6-3']
      - cloud.aws.s3.access_key
      - cloud.aws.s3.secret_key
    deploy:
      placement:
        constraints:
          - node.role == worker
          - engine.labels.availability_zone == ${AWS_REGION}b

volumes:
  es-vol:
    name: "es6-2-vol"
    driver: "cloudstor:aws"
    driver_opts:
      backing: relocatable
      size: 25
      ebstype: gp2
