version: '3.5'

services:
  es6-2:
    image: ${IMAGE_NAME}:${IMAGE_TAG:-latest}
    environment:
      - node.name=${ES_NODE_NAME:-es6-2}
      - node.master=${ES_NODE_MASTER}
      - node.data=${ES_NODE_DATA}
      - node.ingest=${ES_NODE_INGEST}
      - path.data=${ES_PATH_DATA}
      - network.host=${ES_NETWORK_HOST}
      - bootstrap.memory_lock=${ES_BOOTSTRAP_MEMORY_LOCK}
      - xpack.security.enabled=false
      - searchguard.nodes_dn.0=${SG_NODE_1_DN}
      - searchguard.nodes_dn.1=${SG_NODE_2_DN}
      - searchguard.nodes_dn.2=${SG_NODE_3_DN}
      - searchguard.authcz.admin_dn.0=${SG_ADMIN_DN}
      - searchguard.ssl.transport.pemcert_filepath=certs/node.pem
      - searchguard.ssl.transport.pemkey_filepath=certs/node.key
      - searchguard.ssl.transport.pemtrustedcas_filepath=certs/root-ca.pem
      - searchguard.ssl.transport.enforce_hostname_verification=false
      - searchguard.ssl.transport.resolve_hostname=false
      - searchguard.ssl.http.enabled=false
      - searchguard.ssl.http.pemcert_filepath=certs/node.pem
      - searchguard.ssl.http.pemkey_filepath=certs/node.key
      - searchguard.ssl.http.pemtrustedcas_filepath=certs/root-ca.pem
      - searchguard.enable_snapshot_restore_privilege=true
      - searchguard.enterprise_modules_enabled=false
      - discovery.zen.ping.unicast.hosts=${ES_DISCOVERY_ZEN_PING_UNICAST_HOSTS:-es6-1,es6-3}
      - S3_ACCESS_KEY
      - S3_SECRET_KEY
    networks:
      elastic-net:
        aliases:
          - ${ELASTIC_NET_ALIAS:-es6-2}
      metric-net:
    volumes:
      - es-data-vol:${ES_PATH_DATA}
      - es-conf-vol:/usr/share/elasticsearch/config
    secrets:
      - source: ca-pem
        target: /usr/share/elasticsearch/config/certs/root-ca.pem
        mode: 0600
        uid: '1000'
        gid: '1000'
      - source: ca-key
        target: /usr/share/elasticsearch/config/certs/root-ca.key
        mode: 0600
        uid: '1000'
        gid: '1000'
      - source: node-pem
        target: /usr/share/elasticsearch/config/certs/node.pem
        mode: 0600
        uid: '1000'
        gid: '1000'
      - source: node-key
        target: /usr/share/elasticsearch/config/certs/node.key
        mode: 0600
        uid: '1000'
        gid: '1000'
      - source: node-csr
        target: /usr/share/elasticsearch/config/certs/node.csr
        mode: 0600
        uid: '1000'
        gid: '1000'
    logging:
      driver: json-file
    healthcheck:
      test: "[ $(curl --silent localhost:${PORT}/_cat/health?h=status) = 'green' ]"
      interval: 30s
      timeout: 1m
      retries: 20
      start_period: 2m
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        delay: 30s
        window: 3m

networks:
  elastic-net:
    name: ${ELASTIC_NET_NAME:-elastic6-net}
    external: true

  metric-net:
    name: ${METRIC_NET_NAME:-metric-net}
    external: true

secrets:
  ca-pem:
    name: ${CA_PEM_NAME:-ca-pem}
    external: true

  ca-key:
    name: ${CA_KEY_NAME:-ca-key}
    external: true

  node-pem:
    name: ${NODE_PEM_NAME:-node-2-pem}
    file: ./certs/node.pem

  node-key:
    name: ${NODE_KEY_NAME:-node-2-key}
    file: ./certs/node.key

  node-csr:
    name: ${NODE_CSR_NAME:-node-2-csr}
    file: ./certs/node.csr
