version: '3.5'

services:
  elasticsearch-3:
    healthcheck:
      test: curl --silent localhost:${PORT1}/_cluster/health
      timeout: 10s
      retries: 3
      start_period: 2m

volumes:
  elasticsearch-vol:
    name: "elasticsearch-3-vol"
    driver: "cloudstor:aws"
    driver_opts:
      backing: relocatable
      size: 25
      ebstype: gp2
